### ISSUE TITLE
Bad CRC

### ISSUE THREAD

**Issue by stoehrmark** [swilson/aqualogic#1]
Hello Excellent code

I keep getting Bad CRC in the home assistant log. What is this? Is it a problem? It seems to be working
 
thanks

Bad CRC
6:30 PM components/aqualogic.py (WARNING)
Bad CRC
6:07 PM components/aqualogic.py (WARNING)
Bad CRC
6:03 PM components/aqualogic.py (WARNING)
Bad CRC
5:57 PM components/aqualogic.py (WARNING)

**Comment by ramiss** [comment]
Are you sure your RS-485 serial settings are correct?  Hayward/Aqualogic uses:
Baud rate 19200 bps, data size 8 bits, parity none and stop bits 2

The 2 stop bits is not a typical setting.
