### ISSUE TITLE
Tristar VS

### ISSUE THREAD

**Issue by nmbradford** [swilson/aqualogic#8]
Hi - did you ever get anywhere with the TriStar VS rs485 control?  Would be interested to know if you investigated and found if the protocol was same/similar or complete different to the Ecostar pump documented here [EcoStar](http://www.desert-home.com/2014/07/controlling-hayward-ecostar-pump.html)

**Comment by swilson** [comment]
Yes, it is the same. You can see the status messages coming from the pump in FRAME_TYPE_PUMP_STATUS. However there is no direct pump control from this library; it assumes the ProLogic unit is sending the pump speed requests.
